In [1]:
# Data cleaning and wrangling is the same thing
# Make raw data usable
# 1. identify missing data 2. Data Formatting 3.Data Normalization(centering and scaling) 4.Data Binning 
# 5. Turning Categroical Variables to Numeric Variables

In [2]:
import pandas as pd
path="C:\\Users\\ARNOB\\Desktop\\Automobile.csv"
df=pd.read_csv(path)

In [6]:
df["symboling"]

0      3
1      3
2      1
3      2
4      2
      ..
200   -1
201   -1
202   -1
203   -1
204   -1
Name: symboling, Length: 205, dtype: int64

In [7]:
#Additioning works like a grid in pandas
df["symboling"]+1

0      4
1      4
2      2
3      3
4      3
      ..
200    0
201    0
202    0
203    0
204    0
Name: symboling, Length: 205, dtype: int64

In [8]:
df['symboling']=df['symboling']+1

In [9]:
df

,Unnamed: 0,symboling,normalized losses,make,fuel type,aspiration,door numbers,body styles,drive wheels,engine location,...,engine size,fuel system,bore,stroke,compression ratio,horsepower,peak rpm,city mpg,highway mpg,price
0,0,4,?,alfa-romero,gas,std,two,convertible,rwd,front,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,1,4,?,alfa-romero,gas,std,two,convertible,rwd,front,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,2,2,?,alfa-romero,gas,std,two,hatchback,rwd,front,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,3,3,164,audi,gas,std,four,sedan,fwd,front,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,4,3,164,audi,gas,std,four,sedan,4wd,front,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,200,0,95,volvo,gas,std,four,sedan,rwd,front,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,201,0,95,volvo,gas,turbo,four,sedan,rwd,front,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,202,0,95,volvo,gas,std,four,sedan,rwd,front,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,203,0,95,volvo,diesel,turbo,four,sedan,rwd,front,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,204,0,95,volvo,gas,turbo,four,sedan,rwd,front,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625